name: Run BATS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install BATS
        run: |
          git clone --depth 1 https://github.com/bats-core/bats-core.git
          cd bats-core
          ./install.sh "$HOME/bats"

      - name: Add BATS to PATH
        run: echo "$HOME/bats/bin" >> $GITHUB_PATH

      - name: Run BATS tests
        run: bats tests/test_script.bats
