name: BATS Test Runner on macOS

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install BATS
        run: |
          brew install bats-core

      - name: Run BATS tests
        run: bats tests/test_script_macos.bats
